// Helper file to make coverage work for all dart files
// **************************************************************************
// Because of this: https://github.com/flutter/flutter/issues/27997#issue-410722816
// DO NOT EDIT THIS FILE USE: sh scripts/import_files_coverage.sh flutter_ha_dashboard
// **************************************************************************

// ignore_for_file: unused_import

import 'package:flutter_ha_dashboard/main.dart';
import 'package:flutter_ha_dashboard/service_locator.dart';
import 'package:flutter_ha_dashboard/src/app.dart';
import 'package:flutter_ha_dashboard/src/core/domain/context/context.dart';
import 'package:flutter_ha_dashboard/src/core/domain/state_change_dto/state_change_dto.dart';
import 'package:flutter_ha_dashboard/src/core/domain/web_socket_event/web_socket_event.dart';
import 'package:flutter_ha_dashboard/src/core/services/api_service.dart';
import 'package:flutter_ha_dashboard/src/core/services/secure_storage_service.dart';
import 'package:flutter_ha_dashboard/src/core/services/shared_preferences_service.dart';
import 'package:flutter_ha_dashboard/src/core/services/web_socket_service.dart';
import 'package:flutter_ha_dashboard/src/core/state/app_bloc.dart';
import 'package:flutter_ha_dashboard/src/features/areas/domain/area_registries/area_registries.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/data/authentication_repository.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/presentation/account/account_cubit.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/presentation/account/account_screen.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/presentation/connect/connect_button.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/presentation/connect/connect_cubit.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/presentation/connect/connect_form.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/presentation/connect/connect_screen.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/presentation/connect/url_text_field.dart';
import 'package:flutter_ha_dashboard/src/features/devices/domain/device_registries/device_registries.dart';
import 'package:flutter_ha_dashboard/src/features/entities/domain/entity_registries/entity_registries.dart';
import 'package:flutter_ha_dashboard/src/features/entities/domain/entity_states/entity_states.dart';
import 'package:flutter_ha_dashboard/src/features/entities/domain/entity_type.dart';
import 'package:flutter_ha_dashboard/src/features/home/logic/device_filter_list_cubit/device_filter_list_cubit.dart';
import 'package:flutter_ha_dashboard/src/features/home/presentation/area_section_list/area_section.dart';
import 'package:flutter_ha_dashboard/src/features/home/presentation/area_section_list/area_section_list.dart';
import 'package:flutter_ha_dashboard/src/features/home/presentation/device_filter_list/device_filter.dart';
import 'package:flutter_ha_dashboard/src/features/home/presentation/device_filter_list/device_filter_list.dart';
import 'package:flutter_ha_dashboard/src/features/home/presentation/home_screen.dart';
import 'package:flutter_ha_dashboard/src/routing/route_name.dart';
import 'package:flutter_ha_dashboard/src/routing/router.dart';
import 'package:flutter_ha_dashboard/src/theme/base_theme.dart';
import 'package:flutter_ha_dashboard/src/theme/dark_theme.dart';
import 'package:flutter_ha_dashboard/src/theme/light_theme.dart';
import 'package:flutter_ha_dashboard/src/theme/theme_extensions/app_colors.dart';
import 'package:flutter_ha_dashboard/src/theme/theme_extensions/app_font_sizes.dart';
import 'package:flutter_ha_dashboard/src/theme/theme_extensions/app_sizes.dart';
import 'package:flutter_ha_dashboard/src/theme/themes/text_theme.dart';
import 'package:flutter_ha_dashboard/src/utils/app_config.dart';
import 'package:flutter_ha_dashboard/src/utils/build_context_extensions.dart';
import 'package:flutter_ha_dashboard/src/widgets/app_bar/custom_app_bar.dart';
import 'package:flutter_ha_dashboard/src/widgets/async_value/async_value_widget.dart';

void main() {}
