// Helper file to make coverage work for all dart files
// **************************************************************************
// Because of this: https://github.com/flutter/flutter/issues/27997#issue-410722816
// DO NOT EDIT THIS FILE USE: sh scripts/import_files_coverage.sh flutter_ha_dashboard
// **************************************************************************

// ignore_for_file: unused_import

import 'package:flutter_ha_dashboard/main.dart';
import 'package:flutter_ha_dashboard/service_locator.dart';
import 'package:flutter_ha_dashboard/src/app.dart';
import 'package:flutter_ha_dashboard/src/core/routing/route_name.dart';
import 'package:flutter_ha_dashboard/src/core/routing/router.dart';
import 'package:flutter_ha_dashboard/src/core/routing/router_notifier.dart';
import 'package:flutter_ha_dashboard/src/core/services/api_service.dart';
import 'package:flutter_ha_dashboard/src/core/services/secure_storage_service.dart';
import 'package:flutter_ha_dashboard/src/core/services/shared_preferences_service.dart';
import 'package:flutter_ha_dashboard/src/core/state/app_bloc.dart';
import 'package:flutter_ha_dashboard/src/core/utils/app_config.dart';
import 'package:flutter_ha_dashboard/src/core/utils/async_value.dart';
import 'package:flutter_ha_dashboard/src/core/widgets/async_value/async_value_widget.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/data/authentication_repository.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/presentation/account/account_cubit.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/presentation/account/account_screen.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/presentation/sign_in/sign_in_cubit.dart';
import 'package:flutter_ha_dashboard/src/features/authentication/presentation/sign_in/sign_in_screen.dart';

void main() {}
